[workspace]
members = ["cli", "lishp"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Vassiliy Kuzenkov"]
license = "MIT"
repository = "https://github.com/bondiano/lishp"
