[package]
name = "lishp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nom = "8.0.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "parser_bench"
harness = false
