name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt -- --check

  machete:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-machete
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete

      - name: Check for unused dependencies
        run: cargo machete

  cargo-sort:
    name: Dependency Sort Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-sort
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort

      - name: Check dependency sorting
        run: cargo sort -c

  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli

      - name: Check for typos
        run: typos

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests (all targets)
        run: cargo test --all-targets --all-features

      - name: Run doc tests
        run: cargo test --doc

  clippy:
    name: Clippy Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain and clippy
        run: rustup component add clippy

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

